version: "3.8"

services:
  api-db:
    image: mysql:latest
    container_name: api-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_API_PORT}:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  data-db:
    image: mysql:latest
    container_name: data-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_DATA_PORT}:3306"
    volumes:
      - ./db_files:/var/lib/mysql
      - ./init-db-data.sql:/docker-entrypoint-initdb.d/init-db.sql

  db-filler:
    build: .
    container_name: db-filler
    depends_on:
      - api-db
      - data-db
    environment:
      DATABASE_HOST: api-db
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_API_PORT: ${DATABASE_API_PORT}
      DATABASE_DATA_PORT: ${DATABASE_DATA_PORT}
    command: ["sh", "-c", "npm run data:generate && npm run data:etl"]
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true